---
kind: pipeline
name: ubuntu18test

platform:
  os: linux
  arch: amd64

# instance:
#   include:
#     - drone.fdiopoc.net
#     - 5346a318.ngrok.io

steps:
- name: prtest
  image: index.docker.io/snergster/vpp-ubuntu18
  commands:
    - echo 'prtest only'
  when:
    event:
      -pull_request
- name: prandpush
  image: index.docker.io/snergster/vpp-ubuntu18
  commands:
    - echo 'pr and push'
  when:
    event:
    - pull_request
    - push
- name: vpppush
  environment:
    REPO:
      from_secret: repo
    token:
      from_secret: token
  image: index.docker.io/snergster/vpp-ubuntu18
  commands:
    - echo 'push only'
  when:
    event:
    - push
